#!/bin/bash

if [ "$2" = "up" ]; then
	case "$1" in
		usb0)
			ip route del default via 192.168.128.1 dev usb0
			ip route add default via 192.168.128.1 dev usb0 metric 800

			ip route del 192.168.128.0/24 via 0.0.0.0 dev usb0
			ip route add 192.168.128.0/24 via 0.0.0.0 dev usb0 metric 800
			;;
		*)
			;;
	esac
fi
