#!/bin/bash

[ "$IFACE" = "eth0" ] || exit 0

GATEWAY=$(ip route show dev eth0 | awk '/default/ {print $3}')
MASK=$(echo "$GATEWAY" | awk -F'.' '{ $NF=0; print $1"."$2"."$3"."$NF }')
logger "if-up.d: eth0 is up, adjusting default route metric to 700" "$GATEWAY" "$MASK"

if [ -n "$GATEWAY" ]; then
	ip route delete default via "$GATEWAY" dev eth0
	ip route add default via "$GATEWAY" dev eth0 metric 700 onlink

	ip route delete "$MASK"/24 dev eth0
	ip route add "$MASK"/24 via 0.0.0.0 dev eth0 metric 700
fi